apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-new
  labels:
    app: my-deployment-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment-new
  template:
    metadata:
      labels:
        app: my-deployment-new
    spec:
      containers:
      - name: my-deployment-new
        image: azaksacr1.azurecr.io/hello-aks:14
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service 
metadata:
  name: my-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: my-deployment-new
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port         